apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-app
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: web-server
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Nginx K8s App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 40px;
                background-color: #f5f5f5;
            }
            .container {
                background-color: white;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            h1 {
                color: #333;
                text-align: center;
            }
            .info {
                background-color: #e8f4fd;
                padding: 15px;
                border-left: 4px solid #0078d4;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Nginx Kubernetes Application</h1>
            <div class="info">
                <p><strong>Status:</strong> Successfully deployed with ArgoCD!</p>
                <p><strong>Application:</strong> Nginx Web Server</p>
                <p><strong>Deployment:</strong> Kubernetes + ArgoCD</p>
                <p><strong>Environment:</strong> Development</p>
            </div>
            <p>This nginx application is running in a Kubernetes cluster and managed by ArgoCD for GitOps continuous deployment.</p>
        </div>
    </body>
    </html>
