apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/version: "1.25"
  app.kubernetes.io/managed-by: argocd
