apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mesh
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio-mesh
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: service-mesh
    app.kubernetes.io/part-of: nginx-app
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nginx-project
  
  source:
    repoURL: .
    targetRevision: HEAD
    path: istio
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
