apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-app

resources:
- gateway.yaml
- virtual-service.yaml
- destination-rule.yaml

commonLabels:
  app.kubernetes.io/part-of: nginx-istio-mesh
  app.kubernetes.io/managed-by: argocd
