apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-app

resources:
- ../../base

# Development-specific patches
patchesStrategicMerge:
- deployment-patch.yaml

# Development environment settings
replicas:
- name: nginx-v2-deployment
  count: 2

images:
- name: nginx
  newTag: 1.25-alpine

commonLabels:
  environment: development
  app.kubernetes.io/instance: development

configMapGenerator:
- name: nginx-v2-config
  behavior: merge
  literals:
  - ENVIRONMENT=development
  - DEBUG=true
