apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-app

resources:
- ../../base

# Development environment settings
replicas:
- name: nginx-v2-deployment
  count: 2

images:
- name: nginx
  newTag: 1.25-alpine

labels:
- pairs:
    environment: development
    app.kubernetes.io/instance: development
